Feat/home pg button
codedstrings/odin-recipes pull request #4
Opened 2024-08-28 06:55 UTC by PrajaktaUpadhye6

#3 Resolved
Completed suggested changes related to directory.
Shifted index.html page to root directory.

2024-08-30 06:39 UTC, codedstrings requested changes
The image path was updated from "./img/mad-cook.jpg" to "../img/mad-cook.jpg." Since index.html is in the root directory, the original path ./img/mad-cook.jpg is correct. The ../ would look for the img folder outside of the current directory, which isn't accurate in this case. Could you please change it back?

Also, I noticed you closed the previous PR and created a new one. In the future, it's usually easier to continue committing changes to the same PR instead of creating a new one. This helps keep the discussion and review process organized in one place. You just have to commit in the PR branch (feat/HomePg-button) as you normally would, and the changes would reflect in this PR. 

Everything else looks fine to me! Please add the requested change so I can Merge the PR. (be sure to not create a new PR)

2024-08-30 06:39 UTC, codedstrings commented on index.html
> +    <img src="../img/mad-cook.jpg" alt="mad cook experimenting" width="60%">
please make the src = "./img/mad-cook.jpg"

2024-10-04 05:08 UTC, codedstrings commented
@PrajaktaUpadhye6 Hey, I would like to close the issue soon...It'll be greatly helpful if you could please add the requested changes soon.

2024-10-04 17:40 UTC, PrajaktaUpadhye6 commented
Can you check the suggested changes, I have also tried to enhance the UI a bit

2024-10-05 18:29 UTC, codedstrings reviewed
lgtm!

2024-10-05 18:31 UTC, codedstrings approved these changes

2024-10-05 18:48 UTC, merged